before_script:
  - dnf install -y git gcc gcc-c++ make findutils diffutils gawk || (apt-get update && apt-get install -y git gcc g++ make findutils gawk)
  - git submodule update --init --recursive

test:
  script:
  - make test
  - make debug-test
  - make opt-test
  - make release-test

make_only:
  script:
  - make
  - make opt
  - make release
  - make debug

statistics:
  script:
  - make opt-test | grep "Duration per record"

install:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/recorder/ install

install-opt:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/recorder-opt/ install-opt

install-debug:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/recorder-debug/ install-debug

install-release:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/recorder-release/ install-release

test:fedora:
  image: fedora:latest
  script:
  - make test

test-opt:fedora:
  image: fedora:latest
  script:
  - make test-opt

test-release:fedora:
  image: fedora:latest
  script:
  - make test-release

test-debug:fedora:
  image: fedora:latest
  script:
  - make test-debug

build:fedora:
  image: fedora:latest
  script:
  - make

build-opt:fedora:
  image: fedora:latest
  script:
  - make opt

build-debug:fedora:
  image: fedora:latest
  script:
  - make opt-debug

build-release:fedora:
  image: fedora:latest
  script:
  - make opt-release

test:fedora42:
  image: fedora:42
  script:
   - make test

test:fedora43:
  image: fedora:43
  script:
   - make test

test:ubuntu:
  image: ubuntu:24.04
  script:
  - make test

test-opt:ubuntu:
  image: ubuntu:24.04
  script:
  - make test-opt

test-release:ubuntu:
  image: ubuntu:24.04
  script:
  - make test-release

test-debug:ubuntu:
  image: ubuntu:24.04
  script:
  - make test-debug

test:ubuntu25:
  image: ubuntu:25.04
  script:
  - make test

test-opt:ubuntu25:
  image: ubuntu:25.04
  script:
  - make test-opt

test-release:ubuntu25:
  image: ubuntu:25.04
  script:
  - make test-release

test-debug:ubuntu25:
  image: ubuntu:25.04
  script:
  - make test-debug
